default_agent: agentcore_app
agents:
  agentcore_app:
    name: agentcore_app
    entrypoint: agentcore_app.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::711179720646:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-b87a360759
      execution_role_auto_create: false
      account: '711179720646'
      region: us-west-2
      ecr_repository: 711179720646.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-agentcore_app
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_app-VZu3VRA4TG
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:711179720646:runtime/agentcore_app-VZu3VRA4TG
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-agentcore_app-builder
      execution_role: arn:aws:iam::711179720646:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-b87a360759
      source_bucket: bedrock-agentcore-codebuild-sources-711179720646-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
